Feat: refactor codebase
Hope1226/oop-school-library pull request #5
Opened 2022-01-31 22:31 UTC by Hope1226

In this feature branch we: 

- [x] Separated all methods related to people into a new Class `PersonCreator`
- [x] Separated all methods related to books into a new Class `BookCreator`
- [x] Separated all methods related to rentals into a new Class `ReantalCreator`

2022-01-31 23:11 UTC, TedLivist requested changes
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @Hope1226 and @Ntwali-Josue

Good job so far!
✔️ Good documentation
✔️ Classes are defined in different files
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
#### _Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-31 23:11 UTC, TedLivist commented on book_creator.rb
> +    author = gets.chomp
- [ ] In keeping with the SOLID rule, let's refactor this `create_book` method. Kindly extract this code requesting user input into a different method.

  **SUGGESTION:** You can have the method return an array with `title` and `author` variables and then destructure the method here in `create_book` using the **[Splat Operator](https://jsarbada.wordpress.com/2019/02/05/destructuring-with-ruby/)**

2022-01-31 23:11 UTC, TedLivist commented on person_creator.rb
> +    name = gets.chomp
- [ ] In keeping with the Single-responsibility rule, all requests for inputs should be placed in a different method or class whose sole responsibility is to request and validate inputs. Kindly extract these requests for input into another method. After all refactoring, kindly ensure that your app still works the same

2022-02-01 11:57 UTC, hiromataba approved these changes
# Status: Approved :tada:  :champagne:  :confetti_ball: 
Hi @Hope1226  :wave:   :wave: , 

![200w](https://user-images.githubusercontent.com/75126481/151663786-7e0aa330-6769-4ab2-a051-3754be515be9.gif) 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To Highlight :1st_place_medal: 
- Your Pull Request has a proper title and description. ✔️  
- No Linter errors :heavy_check_mark: 
- Your README file looks very professional :+1: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-01 11:59 UTC, merged